[phases.setup]
nixPkgs = ['ffmpeg', 'python3']

[phases.install]
cmds = ['npm install']

[phases.build]
dependsOn = ['install']
cmds = ['cd frontend && npm install && npm run build']

[start]
cmd = 'node backend/server.js'
